deployments: /opt/deployments

# Change this!
api_key: 3821A95D456134214FAD6FA91A2BAFE574D47151

repositories:
  buyappalachian.org:
    branches:
      - torquebox
  ballast-sinatra:
    branches: 
      - master
      - test
