web:
  context: /stompbox
  rackup: /home/ubuntu/code/stompbox/config.ru

environment:
#  Sample configuration options
 AUTO_MIGRATE: true
 DATABASE_URL: postgres://stompbox:stompbox@localhost/stompbox
#  DEPLOYMENTS: /opt/deployments
 REQUIRE_AUTHENTICATION: true
 API_KEY: 8909fe7032f03f2b728d478b0e600896130b933d

